import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Seymour | Изучай, понимай и моделируй обучение нейросетей",
    description: "Generated by create next app",
};

export const Home = () => {
    return (
        <div>Home</div>
    )
}
