'use client';

import { useState } from 'react';
import type { Metadata } from 'next';
import DrawingGrid from '@features/DrawingGrid';

export const metadata: Metadata = {
    title: 'Seymour | Изучай, понимай и моделируй обучение нейросетей',
    description: 'Generated by create next app',
};

export const Hebbian = () => {
    const [x, setX] = useState(Array.from({ length: 5 }, () => Array.from({ length: 3 }, () => 0)));
    return (
        <>
            <h1>Правило Хебба (классификация цифр).</h1>
            <dl>
                <dt>Пояснение к задачи:</dt>
                <dd>
                    подобрать значения синаптических весов wj такими, чтобы выходной сигнал y принимал значение единица,
                    если на карточке было изображено четное число, и ноль, если число было нечетным.
                </dd>
            </dl>
            <DrawingGrid grid={x} setGrid={setX} />
        </>
    );
};
